### ISSUE TITLE
Locale Question

### ISSUE THREAD

**Issue by marcelopalin** [ripjar/material-datetime-picker#120]
Congratulations! This is a beautiful job. I would like to say that the translation to any language works well, just need to include the "moments" file referring to your language. 

Example:
In my case:
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/locale/pt-br.js"></script>
It works fine!

However, the only part of the calendar that is not translated is the days of the week ... section that remain in English. 

[Su Mo Tu We Th Fr Sa] => I need: [Do Se Te Qa Qi Sx Sa]

Do you have any idea how I can fix this? Does the section not use "moments" library to be build?

Thanks, 
Palin
São Paulo/Brazil

**Comment by jwhitfieldseed** [comment]
It looks like an issue with how [rome](https://github.com/bevacqua/rome) builds the calendar component.

It builds the day headers with moment's `weekdaysMin`, which should be `["Dom", "2ª", "3ª", "4ª", "5ª", "6ª", "Sáb"]` for your locale.

When I get a chance I will step through rome's handling to see why it uses the en-gb locale instead of the loaded moment locale.

**Comment by jwhitfieldseed** [comment]
Aha: The packaged `rome.js` script tag from this repo's example contains a copy `moment.js`, which uses the default locale.

The solution is to use `rome.standalone.js` instead. That uses the global `moment`, like the rest of the datepicker. I'll update the demo page.

**Comment by marcelopalin** [comment]
Thanks Joe! Perfect!!
