### ISSUE TITLE
Demo on CSSscript.com - not working in Safari 9 ?

### ISSUE THREAD

**Issue by pepperstreet** [ripjar/material-datetime-picker#41]
Hello, just found your date-picker demo on CSSscript.com  
Unfortunately it does not work at all. I can see the calendar button, but nothing happens on-click.
Is it related to that particular demo only?

Console errors: 

_SyntaxError: Unexpected token '>'
(anonyme Funktion)beautiful-material-design-date-time-picker:86_

_[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (datepicker.css.map, line 0)_

**Comment by Jivings** [comment]
Can you provide me with a url to the demo?

**Comment by pepperstreet** [comment]
Overlooked your comment and email notification, sorry. Here you go:
description page
http://www.cssscript.com/beautiful-material-design-date-time-picker/
demo
http://www.cssscript.com/demo/beautiful-material-design-date-time-picker

**Comment by jwhitfieldseed** [comment]
I'll update the demo page to avoid ES6 syntax so that it works on older version of browsers (the [arrow function usage](https://github.com/ripjar/material-datetime-picker/blob/c758c6b7409b8a9cf96591c4047caf33a6900d59/demo/index.html#L73) causes your particular error).

Unfortunately I can't update sites that have copied older versions of the demo page and wrapped them in advertising  ¯\_(ツ)_/¯
