### ISSUE TITLE
When I open datetime-picker in header always showen one date and time. 

### ISSUE THREAD

**Issue by dihar** [ripjar/material-datetime-picker#86]
Everytime I open datetime, I see one date 10th Jan 2015, but selected another.

Always in open I see:
<img width="463" alt="screen shot 2016-09-08 at 13 16 49" src="https://cloud.githubusercontent.com/assets/12913462/18345966/9b3ceb90-75c6-11e6-81c0-38ad64be46a2.png">
I added default and value configs, but nothing didn't change.

``` js
var startPicker = new MaterialDatePicker({
    default: moment(),
    value: moment()
});
```

Thanks!

**Comment by Jivings** [comment]
Ah oops I think I introduced a bug that means the picker wont set it's default values when you open it. As a work around if you set the date and time to something else then set it back then it should work.

Or you can have a look at the code. The problem is [here](https://github.com/ripjar/material-datetime-picker/blob/master/lib/js/index.js#L185).

Because `this.value` is already the default, it is the same as `m`, so nothing happens.
